name: Cleanup Images
on:
  workflow_dispatch:
  schedule:
    - cron: "21 0 * * 0"
jobs:
  clean:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        versions: [1,2,3,4,5,6,7,8,9,10]
        minorVersion: [0,1,2,3,4,5,6,7,8,9,10]
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          min-versions-to-keep: 50
          package-type: container
          package-name: bossdockerimages
          token: ${{ secrets.REGISTERY_TOKEN_2 }}
          version: ${{ matrix.versions }}
          minor-version: ${{ matrix.minorVersion }}
